language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-lxml python-pip
install:
  # here we don't use the travis virtualenv because that
  # causes us to install lxml again below, doubling the build time
  # when it compiles the native modules from source
  - deactivate
  - sudo pip install xml2rfc
  - gem install kramdown-rfc2629

# command to run tests, e.g. python setup.py test
script: make upload

env:
 global:
 - GH_REF: github.com/tlswg/tls13-spec.git
 - secure: "Im9OMgqGzhrWGvSyaJ3W0/xRjhl39Ylt4ANKP80HznQ9qCsbAUb31BaCv9K9lsmT4gPLMU5e1Gwtsmy1MK6TpBHQVIDluWIdo6wWiNqfY335TOw7ASTVPQGSXDgw1tx3fhNDxTC7wLqIi6muvfHaxWwWG/weXUtkpEyezfyQ2dI="
