language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install xml2rfc && gem install kramdown-rfc2629
# command to run tests, e.g. python setup.py test
script: make upload

env:
 global:
 - GH_REF: github.com/tlswg/tls13-spec.git
 - secure: "Im9OMgqGzhrWGvSyaJ3W0/xRjhl39Ylt4ANKP80HznQ9qCsbAUb31BaCv9K9lsmT4gPLMU5e1Gwtsmy1MK6TpBHQVIDluWIdo6wWiNqfY335TOw7ASTVPQGSXDgw1tx3fhNDxTC7wLqIi6muvfHaxWwWG/weXUtkpEyezfyQ2dI="
